version: '3.8'

services:
  flask_app:
    build: .
    restart: always
    container_name: codeforces_lamp
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    ports:
      - "5008:5008"
    environment:
      - CODEFORCES_API_KEY=${CODEFORCES_API_KEY}
      - CODEFORCES_API_SECRET=${CODEFORCES_API_SECRET}
      - TUYA_ACCESS_ID=${TUYA_ACCESS_ID}
      - TUYA_ACCESS_KEY=${TUYA_ACCESS_KEY}
      - TUYA_BULB_ID=${TUYA_BULB_ID}
